title: Going live
description: Materials for the "W10: Going Live: Live Coding as an (Incredibly) Effective Tool for Teaching Programming" workshop at USCOTS 2021
logo: logo/logo.png
show_downloads: true
theme: jekyll-theme-minimal
plugins:
  - jemoji